project_name: scip-go

dist: release

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
-
  main: ./cmd/scip-go/
  binary: scip-go
  ldflags:
    - -X main.version={{.Version}}
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm64

archives:
- id: tarball
  format: tar.gz
- id: bin
  format: binary
  wrap_in_directory: false
  name_template: "src_{{ .Os }}_{{ .Arch }}"

dockers:
  - ids:
    - scip-go
    image_templates:
    - "nxpkg/scip-go:{{ .Tag }}"
    - "nxpkg/scip-go:v{{ .Major }}"
    - "nxpkg/scip-go:v{{ .Major }}.{{ .Minor }}"
    - "nxpkg/scip-go:latest"
    extra_files:
    - go.mod
    - go.sum
    - cmd
    - internal

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
